service: yygs
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: fabiola-aws-dev
  region: eu-north-1
  iam:
    role: arn:aws:iam::818306886347:role/student-development-role
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc
        payloadVersion: "2.0"
        enableSimpleResponses: true

plugins: 
  - serverless-webpack

package: 
  individually: true

functions:
    getMenu:
      handler: functions/getMenu/index.handler
      events:
        - httpApi:
            path: '/api/menu'
            method: GET
            authorizer: 
              name: customAuthorizer
    filterByCategory:
      handler: functions/filterByCategory/index.handler
      events:
        - httpApi:
            path: '/api/menu/{category}'
            method: GET
            authorizer: 
              name: customAuthorizer
    putOrder:
      handler: functions/putOrder/index.handler
      events: 
        - httpApi:
            path: '/api/putOrder'
            method: POST
            # authorizer: 
            #   name: customAuthorizer
    getSingleOrder:
      handler: functions/getSingleOrder/index.handler
      events: 
        - httpApi:
            path: '/api/order/{orderNr}'
            method: GET
            # authorizer: 
            #   name: customAuthorizer
    filterOrders:
      handler: functions/filterOrders/index.handler
      events: 
        - httpApi:
            path: '/api/filterOrders/{status}'
            method: GET
            # authorizer: 
            #   name: customAuthorizer
    updateOrderStatus:
      handler: functions/updateOrderStatus/index.handler
      events:
        - httpApi: 
            path: "/api/updateOrderStatus"
            method: POST
            # authorizer: 
            #   name: customAuthorizer

    authorizerFunc:
      handler: functions/authorizer/index.handler

resources:
  Resources:
    yygsMenu:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: yygs-menu
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: title
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: id 
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: 'filterByCategory'
            KeySchema:
              - AttributeName: category
                KeyType: HASH
            Projection: 
              ProjectionType: ALL
    yygsOrders:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: yygs-orders
        AttributeDefinitions:
          - AttributeName: orderNr
            AttributeType: S
          - AttributeName: orderStatus
            AttributeType: S
          - AttributeName: timeStamp
            AttributeType: S
        KeySchema:
         - AttributeName: orderNr
           KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: 'filterByStatus'
            KeySchema:
              - AttributeName: orderStatus
                KeyType: HASH
              - AttributeName: timeStamp
                KeyType: RANGE  
            Projection:
              ProjectionType: ALL